# Generated by Django 5.2 on 2025-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishki', '0002_alter_naklonki_options_remove_naklonki_deal_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naklonki',
            name='deal_potential',
            field=models.CharField(choices=[('33', '33%'), ('50', '50%'), ('100', '100%'), ('STOP', 'STOP'), ('MORE', 'Больше')], max_length=5),
        ),
    ]
